### ISSUE TITLE
Bug executor node

### ISSUE THREAD

**Issue by Rezenders** [kas-lab/rosa#58]
```
[executor-3] Traceback (most recent call last):
[executor-3]   File "/home/gus/exp_metacontrol_ws/install/rosa_execute/lib/rosa_execute/executor", line 33, in <module>
[executor-3]     sys.exit(load_entry_point('rosa-execute', 'console_scripts', 'executor')())
[executor-3]   File "/home/gus/exp_metacontrol_ws/build/rosa_execute/rosa_execute/executor_node.py", line 26, in main
[executor-3]     executor.spin()
[executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 279, in spin
[executor-3]     self.spin_once()
[executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 764, in spin_once
[executor-3]     self._spin_once_impl(timeout_sec)
[executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 745, in _spin_once_impl
[executor-3]     handler, entity, node = self.wait_for_ready_callbacks(
[executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 691, in wait_for_ready_callbacks
[executor-3]     return next(self._cb_iter)
[executor-3] ValueError: generator already executing
[executor-3] The following exception was never retrieved: cannot schedule new futures after shutdown
[executor-3] sys:1: RuntimeWarning: coroutine 'Executor._make_handler.<locals>.handler' was never awaited
```

**Comment by Rezenders** [comment]
```
[configuration_executor-3] Traceback (most recent call last):
[configuration_executor-3]   File "/home/gus/exp_metacontrol_ws/install/rosa_execute/lib/rosa_execute/configuration_executor", line 33, in <module>
[configuration_executor-3]     sys.exit(load_entry_point('rosa-execute', 'console_scripts', 'configuration_executor')())
[configuration_executor-3]   File "/home/gus/exp_metacontrol_ws/build/rosa_execute/rosa_execute/configuration_executor_node.py", line 26, in main
[configuration_executor-3]     executor.spin()
[configuration_executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 279, in spin
[configuration_executor-3]     self.spin_once()
[configuration_executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 764, in spin_once
[configuration_executor-3]     self._spin_once_impl(timeout_sec)
[configuration_executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 761, in _spin_once_impl
[configuration_executor-3]     future.result()
[configuration_executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 94, in result
[configuration_executor-3]     raise self.exception()
[configuration_executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
[configuration_executor-3]     self._handler.send(None)
[configuration_executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 418, in handler
[configuration_executor-3]     await call_coroutine(entity, arg)
[configuration_executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 343, in _execute_subscription
[configuration_executor-3]     await await_or_execute(sub.callback, msg)
[configuration_executor-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
[configuration_executor-3]     return callback(*args)
[configuration_executor-3]   File "/home/gus/exp_metacontrol_ws/build/rosa_execute/rosa_execute/configuration_executor.py", line 59, in inner
[configuration_executor-3]     return func(*args, **kwargs)
[configuration_executor-3]   File "/home/gus/exp_metacontrol_ws/build/rosa_execute/rosa_execute/configuration_executor.py", line 168, in event_cb
[configuration_executor-3]     self.execute()
[configuration_executor-3]   File "/home/gus/exp_metacontrol_ws/build/rosa_execute/rosa_execute/configuration_executor.py", line 59, in inner
[configuration_executor-3]     return func(*args, **kwargs)
[configuration_executor-3]   File "/home/gus/exp_metacontrol_ws/build/rosa_execute/rosa_execute/configuration_executor.py", line 174, in execute
[configuration_executor-3]     if reconfig_plan.success is True:
[configuration_executor-3] AttributeError: 'NoneType' object has no attribute 'success'

```
